version: '3'
services:
  mongodb:
    image: techietrainerss/mongo:v1

  redis:
    image: redis:4.0.6

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management-alpine
    ports:
      - "15672:15672" 

  mysql:
    container_name: mysql
    image: techietrainerss/mysql:v1

  catalogue:
    container_name: catalogue
    image: techietrainerss/catalogue:v1
    environment:
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
      - mongodb

  user:
    image: techietrainerss/user:v1
    environment:
      MONGO_URL: "mongodb://mongodb:27017/users"
      REDIS_HOST: redis
    depends_on:
      - mongodb
      - redis

  cart:
    container_name: cart
    image: techietrainerss/cart:v1
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
    depends_on:
      - catalogue
      - redis

  shipping:
    container_name: shipping
    image: techietrainerss/shipping:v1
    depends_on:
      - mysql

  payment:
    container_name: payment
    image: techietrainerss/payment:v1
    environment:
      CART_HOST: cart
      USER_HOST: user
      AMQP_HOST: rabbitmq
    depends_on:
      - cart
      - user
      - rabbitmq

  web:
    image: techietrainerss/web:v1
    depends_on:
      - user
      - catalogue
      - cart
    ports:
      - "8080:80"
